<h1>I AM AGREEING TO FOLLOWING CONDITIONS:</H1><br><hr>
<h3>1. I WILL NOT HARASS ANY JOBSEEKER.<br>
2. I WILL NOT DUPLICATE MY IDENTITY.<br>
3. IF I AM  HIRIG SOMEONE I WILL PAY THEM THEIR SALARY ON TIME.<br>
4. I(EMPLOYER) AM SUPPOSE TO DO THEIR VALIDATION BY CHECKING THEIR IDENTITY CARDS AFTER YOU HIRE THEM. BUT YOU WILL NOT MISUSE THOSE DETAILS.<br>

IF I DO ANY OF THE ABOVE MENTIONED ACTS I AM SUPPOSED TO GO THROUGH LEAGAL ACTIONS TAKEN BY FMO OR THAT JOBSEEKER<br><hr>
</h3>